# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Aleph Infinite
tagline:          'AI'
description:      'Aleph Infinite blabla'
url:              http://aleph.kr
baseurl:          /

author:
  name:           'Aleph Infinite'
  url:            http://aleph.kr

paginate:         5

github:
  repo:           https://github.com/Aleph-Infinite/aleph-infinite.github.io
